modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-zwave-dc-module/bridging
name: Z-Wave Device-Connector Bridged
version: v0.0.1
type: device-connector
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MGW_MQTT_BROKER
          services:
            - mgw-zwave-dc
services:
  mgw-zwave-dc:
    name: mgw-zwave-dc
    image: ghcr.io/senergy-platform/mgw-zwave-dc:v1.0.0
secrets:
  auth:
    type: basic-auth
    targets:
      - refVar: AUTH_USERNAME
        item: username
        services:
          - mgw-zwave-dc
      - refVar: AUTH_PASSWORD
        item: password
        services:
          - mgw-zwave-dc
    userInput:
      name: Auth Credentials
configs:
  mqttBroker:
    dataType: string
    value: "tcp://message-broker:1883"
    targets:
      - refVar: ZWAVE_MQTT_BROKER
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: MQTT Broker
      description: "e.g. tcp://message-broker:1883"
      group: mqtt
  mqttUsername:
    dataType: string
    optional: true
    targets:
      - refVar: ZWAVE_MQTT_USER
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: MQTT Username
      group: mqtt
  mqttPassword:
    dataType: string
    optional: true
    targets:
      - refVar: ZWAVE_MQTT_PW
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: MQTT Password
      group: mqtt
  mqttClientId:
    dataType: string
    value: "mgw-zwave-dc_zwave"
    targets:
      - refVar: ZWAVE_MQTT_CLIENT_ID
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: MQTT ClientID CMD
      group: mqtt
## mgw broker config by dependency
#  mgwMqttBroker:
#    dataType: string
#    value: "tcp://message-broker:1883"
#    targets:
#      - refVar: MGW_MQTT_BROKER
#        services:
#          - mgw-zwave-dc
#    userInput:
#      type: text
#      name: MGW MQTT Broker
#      description: "e.g. tcp://message-broker:1883"
#      group: mqtt
## mgw credentials are empty
#  mgwMqttUsername:
#    dataType: string
#    targets:
#      - refVar: MGW_MQTT_USER
#        services:
#          - mgw-zwave-dc
#    userInput:
#      type: text
#      name: MGW MQTT Username
#      group: mgw
#  mgwMqttPassword:
#    dataType: string
#    targets:
#      - refVar: MGW_MQTT_PW
#        services:
#          - mgw-zwave-dc
#    userInput:
#      type: text
#      name: MGW MQTT Password
#      group: mgw
  mgwMqttClientId:
    dataType: string
    value: "mgw-zwave-dc_mgw"
    targets:
      - refVar: MGW_MQTT_CLIENT_ID
        services:
          - mgw-zwave-dc
  zwaveController:
    dataType: string
    value: "zwavejs2mqtt"
    options:
      - "zwave2mqtt"
      - "zwavejs2mqtt"
    targets:
      - refVar: ZWAVE_CONTROLLER
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Z-Wave Controller
      group: zwave
  zwaveValueEventTopic:
    dataType: string
    value: "zwave2mqtt/#"
    targets:
      - refVar: ZVAVE_VALUE_EVENT_TOPIC
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Z-Wave Value Event Topic
      group: zwave
  zwaveMqttDeviceStateTopic:
    dataType: string
    value: "zwave/#"
    targets:
      - refVar: ZWAVE_MQTT_DEVICE_STATE_TOPIC
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Z-Wave Mqtt Device State Topic
      group: zwave
  zwaveMqttApiTopic:
    dataType: string
    value: "zwave2mqtt/_CLIENTS/ZWAVE_GATEWAY-SENERGY/api"
    targets:
      - refVar: ZWAVE_MQTT_API_TOPIC
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Z-Wave Mqtt Api Topic
      group: zwave
  zwaveNetworksEventsTopic:
    dataType: string
    value: "zwave2mqtt/_EVENTS/ZWAVE_GATEWAY-SENERGY"
    targets:
      - refVar: ZWAVE_NETWORK_EVENTS_TOPIC
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Z-Wave Network Event Topic
      group: zwave
  authUrl:
    dataType: string
    value: "https://auth.senergy.infai.org"
    targets:
      - refVar: AUTH_ENDPOINT
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Auth URL
      group: platform
  permissionSearchUrl:
    dataType: string
    value: "https://api.senergy.infai.org/permissions/query"
    targets:
      - refVar: PERMISSIONS_SEARCH_URL
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Permission Search URL
      group: platform
  deviceManagerUrl:
    dataType: string
    value: "https://api.senergy.infai.org/device-manager"
    targets:
      - refVar: DEVICE_MANAGER_URL
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: Device Manager URL
      group: platform
  debug:
    dataType: string
    value: "true"
    options:
      - "true"
      - "false"
    optionsExt: false
    targets:
      - refVar: DEBUG
        services:
          - mgw-zwave-dc
    userInput:
      type: text
      name: DEBUG
inputGroups: 
  mqtt:
    name: "MQTT"
  mgw:
    name: "MGW"
  platform:
    name: "Platform"
  zwave:
    name: "Z-Wave"